const DataSchedule = [
  {
    id: 1,
    lable: "Class Name",
    className: "Fitness",
    Timelable: "Time",
    timeInfo: "9:00am - 10:00am",
    TrainerLable: "Trainer",
    trainerName: "David Vila",
    Day: "monday",
  },
  {
    id: 2,
    lable: "Class Name",
    className: "Body Building",
    Timelable: "Time",
    timeInfo: "10:00am - 11:00pm",
    TrainerLable: "Trainer",
    trainerName: "Paul Weight",
    Day: "monday",
  },
  {
    id: 3,
    lable: "Class Name",
    className: "Running",
    Timelable: "Time",
    timeInfo: "4:00pm - 5:00pm",
    TrainerLable: "Trainer",
    trainerName: "Junifor Jonas",
    Day: "monday",
  },
  {
    id: 4,
    lable: "Class Name",
    className: "Fitness",
    Timelable: "Time",
    timeInfo: "6:00pm - 7:00pm",
    TrainerLable: "Trainer",
    trainerName: "Brock Lesnar",
    Day: "monday",
  },
  {
    id: 5,
    lable: "Class Name",
    className: "Boxing",
    Timelable: "Time",
    timeInfo: "9:00am - 10:00am",
    TrainerLable: "Trainer",
    trainerName: "Robert Louis",
    Day: "tuesday",
  },
  {
    id: 6,
    lable: "Class Name",
    className: "Yoga",
    Timelable: "Time",
    timeInfo: "11:00am - 12:00pm",
    TrainerLable: "Trainer",
    trainerName: "Ana June",
    Day: "tuesday",
  },
  {
    id: 7,
    lable: "Class Name",
    className: "Crossfit",
    Timelable: "Time",
    timeInfo: "6:00pm - 7:00pm",
    TrainerLable: "Trainer",
    trainerName: "Jenifer Alex",
    Day: "tuesday",
  },
  {
    id: 8,
    lable: "Class Name",
    className: "Cycling",
    Timelable: "Time",
    timeInfo: "9:00am - 10:00am",
    TrainerLable: "Trainer",
    trainerName: "Dorian Yates",
    Day: "wednesday",
  },
  {
    id: 9,
    lable: "Class Name",
    className: "Body Building",
    Timelable: "Time",
    timeInfo: "11:00am - 12:00pm",
    TrainerLable: "Trainer",
    trainerName: "Steven Mark",
    Day: "wednesday",
  },
  {
    id: 10,
    lable: "Class Name",
    className: "Fitness",
    Timelable: "Time",
    timeInfo: "1:00pm - 2:00pm",
    TrainerLable: "Trainer",
    trainerName: "Janelle Cam",
    Day: "wednesday",
  },
  {
    id: 11,
    lable: "Class Name",
    className: "Running",
    Timelable: "Time",
    timeInfo: "4:00pm - 5:00pm",
    TrainerLable: "Trainer",
    trainerName: "Robert Louis",
    Day: "wednesday",
  },
  {
    id: 12,
    lable: "Class Name",
    className: "Crossfit",
    Timelable: "Time",
    timeInfo: "10:00am - 11:00am",
    TrainerLable: "Trainer",
    trainerName: "Ellie Watson",
    Day: "thursday",
  },
  {
    id: 13,
    lable: "Class Name",
    className: "Yoga",
    Timelable: "Time",
    timeInfo: "11:00am - 12:00pm",
    TrainerLable: "Trainer",
    trainerName: "Jonh Lewis",
    Day: "thursday",
  },
  {
    id: 14,
    lable: "Class Name",
    className: "Boxing",
    Timelable: "Time",
    timeInfo: "1:00pm - 2:00pm",
    TrainerLable: "Trainer",
    trainerName: "Becky Lynch",
    Day: "thursday",
  },
  {
    id: 15,
    lable: "Class Name",
    className: "Crossfit",
    Timelable: "Time",
    timeInfo: "9:00am - 10:00am",
    TrainerLable: "Trainer",
    trainerName: "Jecy Deoko",
    Day: "friday",
  },
  {
    id: 16,
    lable: "Class Name",
    className: "Karate",
    Timelable: "Time",
    timeInfo: "10:00am - 11:00am",
    TrainerLable: "Trainer",
    trainerName: "Janelle Cam",
    Day: "friday",
  },
  {
    id: 17,
    lable: "Class Name",
    className: "Meditation",
    Timelable: "Time",
    timeInfo: "1:00pm - 2:00pm",
    TrainerLable: "Trainer",
    trainerName: "Flex Wheeler",
    Day: "friday",
  },
  {
    id: 18,
    lable: "Class Name",
    className: "Workout",
    Timelable: "Time",
    timeInfo: "4:00pm - 5:00pm",
    TrainerLable: "Trainer",
    trainerName: "Shawn Ray",
    Day: "friday",
  },
  {
    id: 19,
    lable: "Class Name",
    className: "Power Lifting",
    Timelable: "Time",
    timeInfo: "9:00am - 10:00am",
    TrainerLable: "Trainer",
    trainerName: "Stefi Cohen",
    Day: "saturday",
  },
  {
    id: 20,
    lable: "Class Name",
    className: "Boxing",
    Timelable: "Time",
    timeInfo: "1:00pm - 2:00pm",
    TrainerLable: "Trainer",
    trainerName: "Monica Jand",
    Day: "saturday",
  },
  {
    id: 21,
    lable: "Class Name",
    className: "Yoga",
    Timelable: "Time",
    timeInfo: "6:00pm - 7:00pm",
    TrainerLable: "Trainer",
    trainerName: "Madison Froning",
    Day: "saturday",
  },
  {
    id: 22,
    lable: "Class Name",
    className: "Body Building",
    Timelable: "Time",
    timeInfo: "10:00am - 11:00am",
    TrainerLable: "Trainer",
    trainerName: "Paul Weight",
    Day: "sunday",
  },
  {
    id: 23,
    lable: "Class Name",
    className: "Running",
    Timelable: "Time",
    timeInfo: "4:00pm - 5:00pm",
    TrainerLable: "Trainer",
    trainerName: "Zinia Zessy",
    Day: "sunday",
  },
  {
    id: 24,
    lable: "Class Name",
    className: "Martial Arts",
    Timelable: "Time",
    timeInfo: "6:00pm - 7:00pm",
    TrainerLable: "Trainer",
    trainerName: "Dorian Yates",
    Day: "sunday",
  },
];
export default DataSchedule;
